version: '3'
    
services:
    backend:
        container_name: meetings_backend
        build: .
        # command: > "python manage.py && python manage.py runserver 0.0.0.0:8000"
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/backend
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: meetings_postgres
        environment:
            - POSTGRES_DB=meetings_db
            - POSTGRES_USER=meetings_admin
            - POSTGRES_PASSWORD=password1